sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    endpoint: ${ALI_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    bucket-name: ${ALI_OSS_BUCKET_NAME:skytake-out-xuan}
    region: ${ALI_OSS_REGION:cn-beijing}